### ISSUE TITLE
Support for (U)EFI PXE clients

### ISSUE THREAD

**Issue by darkcrux** [danderson/pixiecore#8] opened 2015-11-13 10:21 UTC
Hi, 

We're trying out pixiecore to boot up CoreOS on baremetal [QuantaGrid D51PH-1ULH](http://www.qct.io/Product/Storage/Storage-Server/1U/NEW-QuantaGrid-D51PH-1ULH-p334c77c71c150c155?search=D51PH-1ULH&sub_category=71). We're getting this at the moment:

```
2015/11/13 16:13:13 [ProxyDHCP] ParseDHCP: 2c:60:0c:d0:5b:a6 is not an x86 PXE client
2015/11/13 16:13:13 [ProxyDHCP] ParseDHCP: 2c:60:0c:d0:5b:9d is not an x86 PXE client
2015/11/13 16:13:15 [ProxyDHCP] ParseDHCP: 2c:60:0c:d0:5d:05 is not an x86 PXE client
```

Does this mean the PXE client is not supported? I tried commenting out the checks, we could get pixecore (in api mode) to call our API, but it still won't boot up though. 

We've tried pixiecore on VirtualBox and it worked great. My guess is our PXE clients aren't supported. Wondering if there's a way for us to get it working. (not that familiar with the DHCP spec yet).

Please advice. Thanks.

**Comment by darkcrux** [comment] 2015-11-16 07:48
Hmm.. we just got it working. Needed to change some settings in BIOS to use legacy booting instead of UEFI. Not sure how UEFI affects pixiecore though. :thought_balloon:

**Comment by danderson** [comment] 2015-11-24 21:19
This is a known issue, in a sense: pixiecore currently does not support booting EFI clients, mostly because I don't have any EFI-booting machines to test with.

Someone else also ran into this issue, and I think we have a plan on how to add EFI support. Unfortunately, it's a medium-size refactoring to make it work (pixiecore internals need to switch from pxelinux to ipxe for the boot process), and I can't do anything about it until next week when I'm back with my test infrastructure.

But, consider this a "yes, pixiecore should support PXE boot from EFI clients" :).

**Comment by danderson** [comment] 2015-11-24 21:37
The general idea of what needs to be implemented:
 - ProxyDHCP server needs to give different replies for non-ipxe clients ("here's an ipxe blob, please boot it") and ipxe clients ("here's an ipxe config, please execute it").
 - For non-ipxe clients, ProxyDHCP needs to accept 2 new arch types (00:06 for EFI x86 and 00:07 for EFI x86_64), and serve the appropriate compiled iPXE image to each of them. It's questionable whether we should support EFI x86, because those should be incredibly rare, and it forces us to dual-arch all the binaries we serve... Yuck. Seems cleaner to just support 64-bit boot.
 - The TFTP server needs to serve multiple ipxe binaries.
 - The HTTP server needs to serve ipxe configs instead of pxelinux.

The good news is the API for API mode doesn't need to change, because all of this is internal implementation details of the boot process... Unless we add EFI x86 support, because that will force *everything* upstream to start caring about x86 vs x86_64. Which is why I'm inclined to not support it given that it's a small minority.

**Comment by steveeJ** [comment] 2015-11-24 21:42
One argument for supporting multiple architectures would be to be equipped for ARM(64), and other possibly interesting things. Introducing an architecture attribute in the API seems worth an effort, as it's only done once and for all architectures that might follow. With this introduction, it would be wise to make the iPXE blobs external and only ship a couple of defaults. Anyone who cares can then compile their own version of iPXE for their architecture or replace an existing one.

**Comment by danderson** [comment] 2015-11-24 22:09
Yeah, after discussing this with steveeJ, architecture might be reasonable to add.

Thinking at a higher level, this is the constraint I want to keep on the API: a server that implements Pixiecore's API should never know anything about _how_ a machine boots. This gives us freedom to change how pixiecore implements the boot process (as in this bug), and possibly even lets us support non-PXE boot processes (e.g. RedBoot for embedded ARM boards).

The only thing the API server should care about is what the machine _is_ (MAC address X, CPU architecture Y), and _what_ it should boot (kernel X, initrd Y). But the API should never leak any information about _how_ the machine is booting, or how pixiecore is implementing the boot. If it does leak that data, then pixiecore no longer simplifies anything, and it's no better than just running a dhcpd and tftpd in the "traditional" way.

Given this criterion, providing the architecture to the API server is okay (although it increases the complexity of the API server :( ). Providing the machine GUID might be okay, although that's more risky because (a) it's coupled with PXE, so supporting other boot methods might not work and (b) some PXE firmwares report bogus GUIDs, so now the API server has to try and figure out what is going on.

Anyway, as I said, I can't really hack on this until next week, because I'm away from all the machines and weird PXE firmwares I use for testing. I'll look at porting pixiecore to ipxe next week, and revisit the question of extending the API.

**Comment by danderson** [comment] 2016-02-23 05:14
Folks on this bug who have tried to boot EFI machines with Pixiecore: could you get me a packet capture of the initial DHCPDISCOVER that your booting machine sends?

If you're comfortable dissecting packet captures, what I'm actually interested in is the value of DHCP option 93, "Client System Architecture". I'm curious because RFC 4578 says that the value should be 9 for a client that wants an x86-64 EFI binary, but my test machine reports type 7, "EFI ByteCode". The internet suggests that this is a common implementation snafu, and that this actually means "please give me an x86-64 EFI binary", but I'd like to see what machines other than my one test laptop report.

**Comment by heri16** [comment] 2016-07-13 04:58
+1

**Comment by panchoh** [comment] 2016-07-26 12:46
Hi, @danderson.

Here's the DHCP option 93 for an UEFI client, namely HP ProLiant BL460c Gen9, obtained via tcpdump:
`ARCH Option 93, length 2: 7`
which is consistent with what you reported.

Thanks a bunch for bringing pixicore to this universe!  And let me know if there is anything else I can do to help with this issue.

Happy hacking,

**Comment by arnehormann** [comment] 2016-08-10 05:03
I'm also getting a 7 for an x64 Dell system. @danderson if you have existing code or a favored approach for this, I'd like to know about it. Otherwise 'll try to send a PR some time the next weeks with (at least) these changes:
* move all `//go:generate` into `gen.go`, also add `//go:generate go get` for `stringer` and `go-binpack` at the beginning of it
* add a `type Architecture uint16` enum consts, add field `Arch Architecture` and `Class []string` to `dhcpPacket`, run `stringer` over `Architecture` in `gen.go`
* remove option 93 `!= 0` check in `parseDHCP`
* parse and store options 77 and 93 `in parsePXE`
* use `tftp.Handler` instead of `tftp.Blob` to serve BIOS/UEFI iPXE payloads based on Arch != 0 and Class not containing `iPXE`
* in http handler, support retrieval of ipxe config (getting hazy here, I started the other stuff)

**Comment by danderson** [comment] 2016-08-10 05:21
So, I've actually *just* started working on this. It turned out to be _much_ more complex than I anticipated, because of buggy UEFI firmwares. It turns out, you need a fairly different boot process to convince most UEFI stuff to take a ProxyDHCP offer.

I currently have a barebones implementation in http://github.com/google/netboot/cmd/pixiecore-gpl (hardwired to boot tinycore linux, no options at all yet), if you would like to test that it is capable of booting your system (I would _love_ to know especially if it fails, my only UEFI test system is my Lenovo laptop).

I'll be fleshing that implementation out over the next couple of days to get feature parity (github.com/google/netboot is going to be the new home for pixiecore once I port over more than the core boot-management code), I'll update this bug when I have something that's commandline-compatible with this codebase.

**Comment by arnehormann** [comment] 2016-08-10 05:49
Wow, this is great!
I love the ability to use pixiecore as a library. And the pcap lib allows
for tests - esp regression tests with user reported captures.
Amazing!
I'm just browsing through the codebase on my mobile, will run it as soon as
possible.
Two remarks: the package link to tftp points to pcap. And YourAddress in
dhcp should probably be OfferedAddress 😁
Again, thank you so much for this!

Am 10.08.2016 07:21 schrieb "Dave Anderson" <notifications@github.com>:

**Comment by danderson** [comment] 2016-08-10 06:09
That's the plan - the big things I want out of the transition of pixiecore to go.universe.tf (and https://github.com/google/netboot for the hosting side) is: library interface, UEFI support, "quick" templates for common recipes ("I want to boot the latest debian installer / the latest CentOS / memtest86..." that just gets the right files for you), and the ability to have regression tests from real packet captures.

It'll take me a bit of time to get there, I'm oncall this week so my normal hacking hours are instead taken with work... But I'll get there :).

**Comment by arnehormann** [comment] 2016-08-10 15:58
@danderson pixiecore-gpl works on Dell PowerEdge R430; UEFI PXE boot successful. Yeah!
If there's anything more to help, feel free to direct-mention me and I'll try to fit it into my schedule.
I already signed the Google CLA for Go if that's an issue.

**Comment by danderson** [comment] 2016-08-24 09:24
I've implemented this in my v2 of Pixiecore. You can find it at https://github.com/google/netboot/tree/master/pixiecore .

Closing this bug, bug please please please file bugs at https://github.com/google/netboot if you encounter bugs! I've tested the UEFI boot process as much as I can on local machines, but there's nothing like the real world to prove me wrong :).

**Closed by danderson** 2016-08-24 09:24 UTC
Labels: enhancement
